#!/bin/bash

# APP_ROOT is an environmental variable coming from the compose file
echo "app root is ${APP_ROOT}, node modules will be installed into ${NODE_MODULE_PATH}"
cd ${APP_ROOT}
node ./index.js
